#PBS -l walltime=03:00:00
#PBS -l nodes=1:ppn=1
#PBS -A PAS1532
#PBS -j oe

cd $PBS_O_WORKDIR
cd ../
mkdir alignments reference
curl -o pmrk_temp.txt http://nebenfuehrlab.utk.edu/markers/OMS/pm-rk.gb
sed 's/ //g' pmrk_temp.txt | sed -E 's/^[0-9]+//' > pm-rk_temp2.txt
grep -E '^[atgc]{3}' pm-rk_temp2.txt > pm-rk_temp3.txt
echo '>chr1' > header_temp.txt
cat header_temp.txt pm-rk_temp3.txt > reference/pm-rk.fa
rm *temp*

module load hisat2
hisat2-build reference/pm-rk.fa reference/pm-rk

hisat2 -x reference/pm-rk -1 trimmed_fastq/RK10_S2_L001_1P.fastq.gz -2 trimmed_fastq/RK10_S2_L001_2P.fastq.gz -S alignments/hisat2_10.sam --un-conc-gz alignments/paired_unaligned_concord10.fq.gz --al-conc-gz alignments/paired_aligned10.fq.gz --summary-file alignments/summary_10.txt --rg-id gen10 --rg SM:gen10
hisat2 -x reference/pm-rk -1 trimmed_fastq/RK70_S1_L001_1P.fastq.gz -2 trimmed_fastq/RK70_S1_L001_2P.fastq.gz -S alignments/hisat2_70.sam --un-conc-gz alignments/paired_unaligned_concord70.fq.gz --al-conc-gz alignments/paired_aligned70.fq.gz --summary-file alignments/summary_70.txt --rg-id gen70 --rg SM:gen70
