#PBS -l walltime=01:00:00
#PBS -l nodes=1:ppn=1
#PBS -A PAS1532
#PBS -j oe

cd $PBS_O_WORKDIR
cd ../
mkdir genotypes

module load picard
java -jar $PICARD CreateSequenceDictionary R=reference/pm-rk.fa O=reference/pm-rk.dict

cd picard_out
java -jar $PICARD BuildBamIndex I=hisat2_10.sorted.bam
java -jar $PICARD BuildBamIndex I=hisat2_70.sorted.bam
cd ../

module load samtools
cd reference
samtools faidx pm-rk.fa
cd ../

module load gatk/4.1.2.0
gatk HaplotypeCaller -ploidy 2 -I picard_out/hisat2_10.sorted.bam -R reference/pm-rk.fa -O genotypes/pmrk_10_dip.vcf
gatk HaplotypeCaller -ploidy 2 -I picard_out/hisat2_70.sorted.bam -R reference/pm-rk.fa -O genotypes/pmrk_70_dip.vcf
