#PBS -l walltime=01:00:00
#PBS -l nodes=1:ppn=1
#PBS -A PAS1532
#PBS -j oe

cd $PBS_O_WORKDIR
cd ../picard_out
module load samtools

samtools index -b hisat2_10.sorted.bam 
samtools depth -aa -r chr1:1-14403 hisat2_10.sorted.bam > gen10_depths.txt

samtools index -b hisat2_70.sorted.bam 
samtools depth -aa -r chr1:1-14403 hisat2_70.sorted.bam > gen70_depths.txt


i=`pwd`
module load R

(
echo 'setwd("'${i}'")'
echo 'gen10 <- read.table(file="gen10_depths.txt")'
echo 'gen10_avg <- mean(gen10$V3)'
echo 'gen70 <- read.table(file="gen70_depths.txt")'
echo 'gen70_avg <- mean(gen70$V3)'
echo 'out <- data.frame("gen10" = gen10_avg, "gen70" = gen70_avg)'
echo 'write.table(out, file="depths.txt", sep=",", quote=FALSE, col.name=TRUE)'
) > ../job_scripts/depths.R

R CMD BATCH ../job_scripts/depths.R depths.Rout
