#PBS -l walltime=01:00:00
#PBS -l nodes=1:ppn=1
#PBS -A PAS1532
#PBS -j oe

cd $PBS_O_WORKDIR
cd ../

#aligning the unmapped reads from the previous alignment to the ecoli genome
cd reference
curl -o Ecoli.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/350/185/GCA_000350185.1_ASM35018v1/GCA_000350185.1_ASM35018v1_genomic.fna.gz
gunzip Ecoli.fa.gz

module load hisat2
hisat2-build Ecoli.fa Ecoli

cd ../alignments
hisat2 -x ../reference/Ecoli -1 paired_unaligned_concord10.fq.1.gz -2 paired_unaligned_concord10.fq.2.gz -S ecoli_hisat2_10.sam --un-gz ecoli_unpaired_unaligned10.fq.gz --al-gz ecoli_unpaired_aligned10.fq.gz --un-conc-gz ecoli_paired_unaligned_concord10.fq.gz --al-conc-gz ecoli_paired_aligned10.fq.gz --summary-file ecoli_summary_10.txt
hisat2 -x ../reference/Ecoli -1 paired_unaligned_concord70.fq.1.gz -2 paired_unaligned_concord70.fq.2.gz -S ecoli_hisat2_70.sam --un-gz ecoli_unpaired_unaligned70.fq.gz --al-gz ecoli_unpaired_aligned70.fq.gz --un-conc-gz ecoli_paired_unaligned_concord70.fq.gz --al-conc-gz ecoli_paired_aligned70.fq.gz --summary-file ecoli_summary_70.txt
